#!/usr/bin/env bash
set -euo pipefail

# Cursor BYOK Service — one-command installer
# Usage: ./install.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLIST_LABEL="com.cursor.byok.service"
PLIST_PATH="$HOME/Library/LaunchAgents/$PLIST_LABEL.plist"

# --- detect python3 ---
PYTHON_BIN=""
for p in /opt/homebrew/bin/python3 /usr/local/bin/python3; do
    if command -v "$p" &>/dev/null; then
        ver=$("$p" --version 2>&1 | awk '{print $2}')
        major=$(echo "$ver" | cut -d. -f1)
        if [ "$major" -ge 3 ]; then
            PYTHON_BIN="$p"
            break
        fi
    fi
done
if [ -z "$PYTHON_BIN" ]; then
    echo "[ERROR] python3 not found. Install Python 3 first."
    exit 1
fi
echo "[OK] Python: $PYTHON_BIN ($("$PYTHON_BIN" --version 2>&1))"

# --- detect cloudflared ---
CLOUDFLARED_BIN=""
for c in /opt/homebrew/bin/cloudflared /usr/local/bin/cloudflared cloudflared; do
    if command -v "$c" &>/dev/null || [ -x "$c" ]; then
        CLOUDFLARED_BIN="$c"
        break
    fi
done
if [ -z "$CLOUDFLARED_BIN" ]; then
    echo "[ERROR] cloudflared not found. Install with: brew install cloudflared"
    exit 1
fi
echo "[OK] cloudflared: $CLOUDFLARED_BIN ($("$CLOUDFLARED_BIN" --version 2>&1 | head -1)"

# --- gather config ---
echo ""
echo "=== Configuration ==="
read -rp "Bailian API key [sk-xxx]: " API_KEY
read -rp "Domain (e.g. alexwuyh.dpdns.org): " DOMAIN
read -rp "Subdomain prefix [cursor]: " SUBDOMAIN
SUBDOMAIN="${SUBDOMAIN:-cursor}"
read -rp "Tunnel name [bailian-proxy]: " TUNNEL_NAME
TUNNEL_NAME="${TUNNEL_NAME:-bailian-proxy}"

FULL_HOSTNAME="${SUBDOMAIN}.${DOMAIN}"
echo ""
echo "Public URL will be: https://${FULL_HOSTNAME}/v1"

# --- cloudflared auth ---
CERT_PATH="$HOME/.cloudflared/cert.pem"
if [ ! -f "$CERT_PATH" ]; then
    echo ""
    echo "[INFO] Cloudflare authentication required."
    echo "  A browser will open — select your domain zone to authorize."
    "$CLOUDFLARED_BIN" tunnel login
else
    echo "[OK] Cloudflare cert found at $CERT_PATH"
fi

# --- create tunnel ---
TUNNEL_ID=""
EXISTING=$("$CLOUDFLARED_BIN" tunnel list 2>&1 | grep "$TUNNEL_NAME" || true)
if [ -n "$EXISTING" ]; then
    TUNNEL_ID=$(echo "$EXISTING" | awk '{print $1}')
    echo "[OK] Tunnel '$TUNNEL_NAME' already exists (ID: $TUNNEL_ID)"
else
    echo "[INFO] Creating tunnel '$TUNNEL_NAME'..."
    "$CLOUDFLARED_BIN" tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$("$CLOUDFLARED_BIN" tunnel list 2>&1 | grep "$TUNNEL_NAME" | awk '{print $1}')
    echo "[OK] Tunnel created (ID: $TUNNEL_ID)"
fi

# --- route DNS ---
echo "[INFO] Routing DNS for ${FULL_HOSTNAME}..."
"$CLOUDFLARED_BIN" tunnel route dns "$TUNNEL_NAME" "$FULL_HOSTNAME" 2>&1 || true

# --- write cloudflared config ---
# NOTE: cloudflared config (cf-config.yml) is auto-generated by the service
# script at startup from config.json. No separate ~/.cloudflared/config.yml
# needed. The service derives tunnel UUID, hostname, and credentials path
# from config.json automatically.
echo "[OK] cloudflared config will be auto-generated by service at startup"

# --- write config.json ---
cat > "$SCRIPT_DIR/config.json" << JSONEOF
{
  "model_map": {
    "bl-llm-1": "glm-5.2",
    "bl-llm-2": "kimi-k2.7-code"
  },
  "bailian_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
  "bailian_api_key": "$API_KEY",
  "listen_port": 8787,
  "tunnel_name": "$TUNNEL_NAME",
  "hostname": "$FULL_HOSTNAME",
  "cloudflared_bin": "$CLOUDFLARED_BIN",
  "run_tunnel": true
}
JSONEOF
echo "[OK] config.json written to $SCRIPT_DIR/config.json"

# --- generate launchd plist ---
cat > "$PLIST_PATH" << PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$PYTHON_BIN</string>
        <string>$SCRIPT_DIR/cursor-byok-service.py</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>ProcessType</key>
    <string>Background</string>
    <key>StandardOutPath</key>
    <string>$SCRIPT_DIR/service.log</string>
    <key>StandardErrorPath</key>
    <string>$SCRIPT_DIR/service.log</string>
</dict>
</plist>
PLISTEOF
echo "[OK] launchd plist written to $PLIST_PATH"

# --- load service ---
launchctl unload "$PLIST_PATH" 2>/dev/null || true
sleep 1
launchctl load "$PLIST_PATH"
echo "[OK] Service loaded — will auto-start on boot"

# --- wait and test ---
echo ""
echo "[INFO] Waiting for services to start..."
sleep 8

echo "--- service log ---"
tail -20 "$SCRIPT_DIR/service.log" 2>/dev/null || echo "(no log yet)"

echo ""
echo "--- local test ---"
curl -s -m 10 http://127.0.0.1:8787/v1/models 2>&1 || echo "(local test failed)"

echo ""
echo "--- public test ---"
curl -s -m 15 --noproxy '*' "https://${FULL_HOSTNAME}/v1/models" 2>&1 || echo "(public test failed)"

echo ""
echo "=== Done ==="
echo "Cursor settings:"
echo "  Override OpenAI Base URL: https://${FULL_HOSTNAME}/v1"
echo "  Custom models: bl-llm-1, bl-llm-2"
echo ""
echo "Manage service:"
echo "  launchctl list | grep $PLIST_LABEL   # check status"
echo "  launchctl unload $PLIST_PATH          # stop"
echo "  launchctl load $PLIST_PATH            # start"
